// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My_new_API.Data;

#nullable disable

namespace My_new_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250226052534_region-seed-new")]
    partial class regionseednew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("My_new_API.Models.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a71142f7-7059-4fc3-8fd8-8e85711d808c"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("4efe3c60-a3d2-4570-b20f-8ed8dd8f53d0"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("fd19b7a2-558a-44e2-81c0-44481088558a"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("My_new_API.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6008a2a4-c3f1-48d7-90c1-3ae57bdbc710"),
                            Code = "IND",
                            ImageUrl = "https://www.gettyimages.in/detail/illustration/india-map-royalty-free-illustration/1147562559?adppopup=true",
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("2a75c676-0cfd-434b-b4c4-eff4475c33d8"),
                            Code = "CND",
                            ImageUrl = "https://www.alamy.com/stock-photo/canada-map.html?sortBy=relevant",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("5ff782a8-3d4f-44c8-bbcc-6e01d9967078"),
                            Code = "MLS",
                            ImageUrl = "https://www.shutterstock.com/search/malaysia-map",
                            Name = "Malaysia"
                        });
                });

            modelBuilder.Entity("My_new_API.Models.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LengthInKm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("walks");
                });

            modelBuilder.Entity("My_new_API.Models.Walk", b =>
                {
                    b.HasOne("My_new_API.Models.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("My_new_API.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
